jwt:
  secret: ${JWT_SECRET:testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest}
  access-expiration-sec: 86400
  refresh-expiration-sec: 2592000

kakao:
  client_id: ${KAKAO_LOGIN_CLIENT_ID}
  redirect_uri: ${KAKAO_LOGIN_REDIRECT_URI}

  api:
    key: ${KAKAO_MAP_API_KEY}
    base-url: "https://dapi.kakao.com"

  url:
    auth: "https://kauth.kakao.com"
    api: "https://kapi.kakao.com"

gemini:
  model-name: "gemini-2.5-flash-lite"
  api:
    key: ${GEMINI_API_KEY}
    base-url: "https://generativelanguage.googleapis.com"

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}