jwt:
  secret: ${JWT_SECRET:testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest}
  access-expiration-ms: 86400000
  refresh-expiration-ms: 2592000000

kakao:
  client_id: ${KAKAO_LOGIN_CLIENT_ID}
  redirect_uri: ${KAKAO_LOGIN_REDIRECT_URI}

  api:
    key: ${KAKAO_MAP_API_KEY}
    base-url: "https://dapi.kakao.com"

  url:
    auth: "https://kauth.kakao.com"
    api: "https://kapi.kakao.com"

gemini:
    model-name: "gemini-1.5-pro-latest"
    api:
      key: ${GEMINI_API_KEY}
      base-url: "https://generativelanguage.googleapis.com"